### ISSUE TITLE
messages pending write and sent once channel close is called

### ISSUE THREAD

**Issue by chamarts** [ruanhao/py-netty#1]
Hi,

is this project in use ? I am trying to send server few messages but all the messages are struck in pending and once the channel close is issued, the messages are sent to the server. is this a feature or a bug or do I need to enable any flags while creating a bootstrap connection with the channel ?

thx in advance. appreciate your contribution to the project.

**Comment by ruanhao** [comment]
I have tried example code in README on Linux/Mac/Windows and it seems ok.
Could you show the code for example?
